language: python
python:
  - 2.7
services:
    - mysql
install:
    - pip install -r requirements.txt
script:  py.test
notifications:
    irc:
        channels:
            - "irc.freenode.org#majerteam-travis"
        on_success: change

branches:
    only:
        - master
